services:
  - type: web
    name: silmedy-web
    env: node
    plan: free
    buildCommand: "npm install && npm run build"
    startCommand: "npm run start"       # next start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        fromService: true
      - key: NEXT_PUBLIC_FIREBASE_API_KEY
        fromService: true
      - key: NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
        fromService: true
      - key: NEXT_PUBLIC_FIREBASE_PROJECT_ID     ← 포함
        fromService: true
      - key: NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
        fromService: true
      - key: NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
        fromService: true
      - key: NEXT_PUBLIC_FIREBASE_APP_ID
        fromService: true
      - key: NEXT_PUBLIC_FIREBASE_DATABASE_URL   ← 포함
        fromService: true
      - key: NEXT_PUBLIC_S3_ACCESS_KEY
        fromService: true
      - key: NEXT_PUBLIC_S3_SECRET_KEY
        fromService: true
      - key: NEXT_PUBLIC_S3_REGION
        fromService: true
      - key: NEXT_PUBLIC_S3_BUCKET
        fromService: true